version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      FLASK_APP: "run.py"
      FLASK_RUN_HOST: "0.0.0.0"
      MONGO_URI: "mongodb://localhost:27018"
      MONGO_USERNAME: "root"
      MONGO_PASSWORD: "example"
      MONGO_DBNAME: "mydatabase"

  mongo:
    image: mongo
    restart: always
    hostname: localhost
    ports:
      - "27018:27017"
    command: mongod
    volumes:
      - ./data:/data/db
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
