version: '3.8'

services:
  weather_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      FLASK_APP: "run.py"
      FLASK_RUN_HOST: "0.0.0.0"
      MONGO_URI: "mongodb://host.docker.internal:27017/weather"
      MONGO_DBNAME: "weather"
    command: sh -c "python populate_mongo_data.py && flask run --port 5001"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
